#!/bin/bash

# Usage: ./spit_dependency_updates.sh <path-to-maven-project>

PROJECT_DIR=$1
REPORT="spit-dependency-updates-report.txt"

if [ -z "$PROJECT_DIR" ]; then
  echo "Usage: $0 <path-to-maven-project>"
  exit 1
fi

cd "$PROJECT_DIR" || { echo "Invalid project directory: $PROJECT_DIR"; exit 1; }

echo "# SPIT Dependency Update Report" > "$REPORT"
echo "Scanned Project: $PROJECT_DIR" >> "$REPORT"
echo "" >> "$REPORT"

# Check if Maven is installed
if ! command -v mvn &> /dev/null; then
  echo "Maven is not installed. Please install Maven to run this script."
  exit 1
fi

# Run the Maven Versions plugin
mvn versions:display-dependency-updates -DprocessPlugins=false > mvn-output.txt

# Extract and clean up relevant update info
echo "## Available Dependency Updates:" >> "$REPORT"
grep -A 100 "The following dependencies in Dependencies have newer versions:" mvn-output.txt |   sed '/^$/q' | sed 's/^/ - /' >> "$REPORT"

echo "" >> "$REPORT"
echo "_Generated by SPIT Dependency Update Checker_" >> "$REPORT"
rm -f mvn-output.txt

echo "Dependency update report generated: $REPORT"
