#!/bin/bash

# Usage: ./spit_unused_dependencies.sh <path-to-maven-project>

PROJECT_DIR=$1
REPORT="spit-unused-dependencies-report.txt"

if [ -z "$PROJECT_DIR" ]; then
  echo "Usage: $0 <path-to-maven-project>"
  exit 1
fi

cd "$PROJECT_DIR" || { echo "Invalid project directory: $PROJECT_DIR"; exit 1; }

echo "# SPIT Unused Dependencies Report" > "$REPORT"
echo "Scanned Project: $PROJECT_DIR" >> "$REPORT"
echo "" >> "$REPORT"

# Check if Maven is installed
if ! command -v mvn &> /dev/null; then
  echo "Maven is not installed. Please install Maven to run this script."
  exit 1
fi

# Run the Maven dependency analysis
mvn dependency:analyze > mvn-deps-output.txt

# Extract the unused declared dependencies
echo "## Unused Declared Dependencies:" >> "$REPORT"
grep -A 100 "Unused declared dependencies found:" mvn-deps-output.txt |   sed '/^$/q' | sed 's/^/ - /' >> "$REPORT"

echo "" >> "$REPORT"
echo "_Generated by SPIT Unused Dependency Detector_" >> "$REPORT"
rm -f mvn-deps-output.txt

echo "Unused dependency report generated: $REPORT"
