#!/bin/bash

# Usage: ./spit_circuit_breakers.sh <path-to-java-project>

PROJECT_DIR=$1
REPORT="spit-circuit-breakers-report.md"

if [ -z "$PROJECT_DIR" ]; then
  echo "Usage: $0 <path-to-java-project>"
  exit 1
fi

cd "$PROJECT_DIR" || { echo "Invalid project directory: $PROJECT_DIR"; exit 1; }

echo "# SPIT Circuit Breaker Usage Report" > "$REPORT"
echo "Scanned Project: \`$PROJECT_DIR\`" >> "$REPORT"
echo "" >> "$REPORT"

echo "## Detected Circuit Breaker Patterns" >> "$REPORT"
echo "" >> "$REPORT"

# Look for common circuit breaker annotations or classes
grep -rn "@CircuitBreaker" . --include="*.java" | sed 's/^/- /' >> "$REPORT"
grep -rn "@HystrixCommand" . --include="*.java" | sed 's/^/- /' >> "$REPORT"
grep -rn "@Retry" . --include="*.java" | sed 's/^/- /' >> "$REPORT"
grep -rn "Resilience4j" . --include="*.java" | sed 's/^/- /' >> "$REPORT"

# Look for class names that might imply circuit breaker integration
grep -rnE 'io.github.resilience4j|org.springframework.retry|com.netflix.hystrix' . --include="*.java" | sed 's/^/- /' >> "$REPORT"

echo "" >> "$REPORT"
echo "_Generated by SPIT Circuit Breaker Detector_" >> "$REPORT"
echo "Circuit breaker report written to: $REPORT"
